# Campbell (Windows 10 default)

# Default colors
[colors.primary]
background = '#0c0c0c'
foreground = '#cccccc'

# Normal colors
[colors.normal]
black      = '#0c0c0c'
red        = '#f7685d'
green      = '#6DC45E'
yellow     = '#f7f57b'
blue       = '#63b3f9'
magenta    = '#fa7bfc'
cyan       = '#3a96dd'
white      = '#cccccc'

# Bright colors
[colors.bright]
black      = '#767676'
red        = '#f7685d'
green      = '#6DC45E'
yellow     = '#f7f57b'
blue       = '#63b3f9'
magenta    = '#fa7bfc'
cyan       = '#61d6d6'
white      = '#f2f2f2'
