#!/bin/zsh

# Profile file. Runs on login. Environmental variables are set here.

# Adds `~/.local/bin` to $PATH
export PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"

# Default programs:
export EDITOR="nvim"
export VISUAL="nvim"
export TERMINAL="alacritty"
export TERMINAL_PROG="alacritty"
export BROWSER="brave"

# Other important variables:

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"
export ZDOTDIR="$HOME/.config/zsh"
export QT_QPA_PLATFORMTHEME="qt6ct"
export AWS_CONFIG_FILE="$HOME/.config/aws/config"

# File with system-specific settings
export SYSTEM_PROFILE="$HOME/.zshenv.local"

if [[ -f "$SYSTEM_PROFILE" ]]; then
    source "$SYSTEM_PROFILE"
fi
