#!/bin/bash

#green color
COLOR_GE80=${COLOR_GE80:-#00FF00}

INTERFACE=$(nmcli device | grep connected | grep -v "loopback" | awk '{print $1}')

#print ip address
ADDRESS=$(ip addr show $INTERFACE | grep "inet " | head -n 1 | awk '{print $2}')

# if wifi is connected, print SSID
if [[ -z $(nmcli device | grep wifi) ]] then
    echo "$INTERFACE @ $ADDRESS"
    echo "$INTERFACE @ $ADDRESS"
else 
    SSID="$(iw wlo1 info | grep ssid | awk '{print $2}') @"
    echo  "${SSID} ${ADDRESS}"
    echo  "${SSID} ${ADDRESS}"
fi

echo $COLOR_GE80
