import = [
    "~/.config/alacritty/themes/themes/campbell.toml"
]

[font]
size = 8.5

[font.bold]
family = "Liberation Mono"

[font.italic]
family = "Liberation Mono"

[font.normal]
# family = "Ubuntu Mono Nerd Font"
family = "Liberation Mono"
style = "Regular"

[window]
opacity = 0.9

[window.padding]
x = 6
y = 6

[keyboard]
bindings = [{ key = "k", mods = "Alt", action = "ScrollHalfPageUp" },
            { key = "j", mods = "Alt", action = "ScrollHalfPageDown"},
            { key = "u", mods = "Alt", action = "ScrollToTop"},
            { key = "d", mods = "Alt", action = "ScrollToBottom"},
            { key = "c", mods = "Alt", action = "Copy"},
            { key = "v", mods = "Alt", action = "Paste"},
            { key = "l", mods = "Alt", action = "Right"},
]
