
[font]
size = 11

[font.bold]
family = "Liberation Mono"

[font.italic]
family = "Liberation Mono"

[font.normal]
# family = "Ubuntu Mono Nerd Font"
family = "Liberation Mono"
style = "Regular"

[window]
opacity = 0.9

[window.padding]
x = 6
y = 6

[general]
import = [
    "~/.config/alacritty/themes/themes/campbell.toml"
]
