require("ramiro.plugins-setup")
require("ramiro.core.options")
require("ramiro.core.keymaps")
require("ramiro.core.colorscheme")
require("ramiro.plugins.comment")
require("ramiro.plugins.nvim-tree")
require("ramiro.plugins.lualine")
require("ramiro.plugins.telescope")
require("ramiro.plugins.nvim-cmp")
require("ramiro.plugins.lsp.mason")
require("ramiro.plugins.lsp.lspconfig")
require("ramiro.plugins.lsp.null-ls")
require("ramiro.plugins.autopairs")
require("ramiro.plugins.treesitter")
require("ramiro.plugins.gitsigns")
require("ramiro.plugins.vimtex")
require("ramiro.plugins.catpuccin")
require("ramiro.plugins.toggleterm")
require("ramiro.plugins.harpoon")
-- vim.cmd.colorscheme("nightfly")
vim.cmd("colorscheme tokyonight-night")
